name: Build app

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Prepare output directory
      run: mkdir dist

    - name: Build
      run: go build -v -o dist/preview-imager .

    - name: Copy fonts
      run: cp -r fonts dist/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: preview-imager
        path: dist/
  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: preview-imager
          path: dist/

      - name: Set permissions
        run: chmod +x dist/preview-imager

      - name: List artifact structure
        run: ls -alhR dist/

      - name: Pack all files
        run: tar czvf preview-imager.tar.gz -C dist/ .

      - name: Upload a Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: preview-imager_published
          path: preview-imager.tar.gz
